---
title: "Applied Predictive Modelling Data Preprocessing"
output:
  html_document: default
  html_notebook: default
---

```{r load packages}
# install.packages("caret")
# install.packages("corrplot")
# install.packages("e1071")
# install.packages("lattice")
# install.packages("feather")

library(caret)
library(corrplot)
library(e1071)
library(lattice)
library(tibble)
library(stringr)
library(feather)
```

```{r search functions}
# find existing functions of interest
apropos("confusion")

# find a function in any package
RSiteSearch("confusion", restrict = "functions") # will search website
```

```{r read in data}
segmentationOriginal <- read.csv("segmentationOriginal.csv")

# save as a feather file
write_feather(segmentationOriginal, "segmentationOriginal.feather")

```

```{r change column names}
colNames <- colnames(segmentationOriginal)
colnames(segmentationOriginal) <- str_replace(colNames, "MorphologyV2Cell.", "")
colNames <- colnames(segmentationOriginal)
```

```{r format input}
segData <- subset(segmentationOriginal, Case == 'Train')
cellID <- segmentationOriginal$X
case <- segmentationOriginal$Case

# remove the columns 
segData <- segData[, -c(1:3)]

# remove columns with "status" in the name
status <- grep("Status", colnames(segData))

segData <- segData[, -status]
```

```{r transformations}
# check skewness of a single variable
e1071::skewness(segData$AngleCh1)

# check skewness of multiple columns
skewValues <- apply(segData, 2, e1071::skewness)

head(skewValues)

# visualise heavily skewed variables: AreaCh1, EqSphereVolCh1; plot histogram
lattice::histogram(segData$AreaCh1)
lattice::histogram(segData$EqSphereVolCh1)
```

```{r calculate lamda}
# transformation required: calculate lamda for boxcox transformation
areach1trans <- caret::BoxCoxTrans(segData$AreaCh1)
areach1trans
```

```{r before and after boxcox transformation}
head(segData$AreaCh1)

stats::predict(areach1trans, head(segData$AreaCh1))

(819^(-.9) - 1)/(-.9)
```

```{r pca_run_analysis}
# centre and scale variables before pca analysis
preproc <- caret::preProcess(segData, method = c("center", "scale"))
segData <- stats::predict(preproc, segData)

# use base r function prcomp to perform pca
pcaObject <- stats::prcomp(segData, center = TRUE, scale. = TRUE)

glimpse(pcaObject)
```

```{r pca_sdev}
percentVariance <- pcaObject$sdev^2/sum(pcaObject$sdev^2)*100
head(percentVariance)
```

```{r pca_x and pca_rotation}
# x: stores transformed values
head(pcaObject$x[, 1:5])

# rotation: stores variable loadings
head(pcaObject$rotation[, 1:5])
```

```{r spatial sign}
spatialTrans <- caret::spatialSign(segData)
head(spatialTrans[,1:5])
```

```{r filtering}
# get rid of variables with near zero variance (do not add information but could be problematic for some algorithms)
nearZeroVar(segData)
```
```{r correlations}
correlations <- cor(segData)
corrplot(correlations, order = "hclust")
```

```{r delete variables with high correlation}
highCorr <- findCorrelation(correlations, cutoff = .75)
length(highCorr)
head(highCorr)
filteredSegData <- segData[, -highCorr]
```
```{r creating dummy variables}
data("cars")

head(cars)
```

